load(
    "@rules_graalvm//graalvm:defs.bzl",
    "native_image",
)
load("@rules_java//java:java_binary.bzl", "java_binary")
load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "java",
    srcs = ["Main.java"],
)

java_binary(
    name = "main",
    main_class = "Main",
    runtime_deps = [
        ":java",
    ],
)

native_image(
    name = "main-native",
    main_class = "Main",
    deps = [":java"],
)

alias(
    name = "sample",
    actual = "main-native",
)
