"""Per-Bazel-version shim providing `CcInfo`, `cc_common`, and `JavaInfo`.

Bazel 9 removed the native `CcInfo` global and gutted the native `cc_common`,
requiring loads from `@rules_cc//cc/common`. Those rules_cc files transitively
reference native symbols (e.g. `CcSharedLibraryHintInfo`) that do not exist
before Bazel 7, so an unconditional load would break Bazel 5/6. Likewise,
loading `JavaInfo` from `@rules_java//java:defs.bzl` transitively parses
rules_java files that reference `JavaPluginInfo` (native symbol added in
Bazel 5), breaking Bazel 4. Starlark loads are parse-time and unconditional,
so we take the same approach as `bazel_features`: a repository rule inspects
`native.bazel_version` and writes a `cc_shim.bzl` whose body differs by
version, routing through the native symbols on older Bazel and through
`@rules_cc` / `@rules_java` loads on Bazel 9+.
"""

# Bazel 9+: CcInfo and cc_common are removed; JavaInfo also moved under
# rules_java's `java/common` path.
_MODERN_SHIM = '''"Auto-generated by rules_graalvm cc_shim for Bazel {version}."

load("@rules_cc//cc/common:cc_info.bzl", _CcInfo = "CcInfo")
load("@rules_cc//cc/common:cc_common.bzl", _cc_common = "cc_common")
load("@rules_java//java/common:java_info.bzl", _JavaInfo = "JavaInfo")

cc_shim = struct(
    CcInfo = _CcInfo,
    cc_common = _cc_common,
    JavaInfo = _JavaInfo,
)
'''

# Bazel 5–8: CcInfo / cc_common are native, JavaInfo is available via
# @rules_java//java:defs.bzl (transitively pulls in JavaPluginInfo).
_NATIVE_WITH_RULES_JAVA_SHIM = '''"Auto-generated by rules_graalvm cc_shim for Bazel {version}."

load("@rules_java//java:defs.bzl", _JavaInfo = "JavaInfo")

# buildifier: disable=native-cc
cc_shim = struct(
    CcInfo = CcInfo,
    cc_common = cc_common,
    JavaInfo = _JavaInfo,
)
'''

# Bazel 4: `JavaInfo` is a native global; rules_java 5.x's transitive loads
# reference `JavaPluginInfo`, which was not introduced natively until Bazel 5.
# To avoid that transitive parse, reference the native `JavaInfo` directly.
_NATIVE_SHIM = '''"Auto-generated by rules_graalvm cc_shim for Bazel {version}."

# buildifier: disable=native-cc
cc_shim = struct(
    CcInfo = CcInfo,
    cc_common = cc_common,
    JavaInfo = JavaInfo,
)
'''

def _parse_major(version):
    core = version.split("-")[0]
    first = core.split(".")[0]
    return int(first) if first.isdigit() else 0

def _cc_shim_repo_impl(rctx):
    version = rctx.attr.bazel_version or native.bazel_version or "99.0.0"
    major = _parse_major(version)
    if major >= 9:
        template = _MODERN_SHIM
    elif major >= 5:
        template = _NATIVE_WITH_RULES_JAVA_SHIM
    else:
        template = _NATIVE_SHIM
    rctx.file("BUILD.bazel", 'exports_files(["cc_shim.bzl"])\n')
    rctx.file("cc_shim.bzl", template.format(version = version))

cc_shim_repo = repository_rule(
    implementation = _cc_shim_repo_impl,
    # `local = True` re-evaluates on server restart so `native.bazel_version` stays current.
    local = True,
    attrs = {
        "bazel_version": attr.string(
            doc = "Override Bazel version for testing; falls back to `native.bazel_version`.",
        ),
    },
)
