"""Per-Bazel-version shim providing `CcInfo` and `cc_common`.

Bazel 9 removed the native `CcInfo` global and gutted the native `cc_common`,
requiring loads from `@rules_cc//cc/common`. Those rules_cc files transitively
reference native symbols (e.g. `CcSharedLibraryHintInfo`) that do not exist
before Bazel 7, so an unconditional load would break Bazel 5/6. Starlark loads
are parse-time and unconditional, so we take the same approach as
`bazel_features`: a repository rule inspects `native.bazel_version` and writes
a `cc_shim.bzl` whose body differs by version.
"""

_MODERN_SHIM = '''"Auto-generated by rules_graalvm cc_shim for Bazel {version}."

load("@rules_cc//cc/common:cc_info.bzl", _CcInfo = "CcInfo")
load("@rules_cc//cc/common:cc_common.bzl", _cc_common = "cc_common")

cc_shim = struct(
    CcInfo = _CcInfo,
    cc_common = _cc_common,
)
'''

_NATIVE_SHIM = '''"Auto-generated by rules_graalvm cc_shim for Bazel {version}."

# buildifier: disable=native-cc
cc_shim = struct(
    CcInfo = CcInfo,
    cc_common = cc_common,
)
'''

def _parse_major(version):
    core = version.split("-")[0]
    first = core.split(".")[0]
    return int(first) if first.isdigit() else 0

def _cc_shim_repo_impl(rctx):
    version = rctx.attr.bazel_version or native.bazel_version or "99.0.0"
    template = _MODERN_SHIM if _parse_major(version) >= 9 else _NATIVE_SHIM
    rctx.file("BUILD.bazel", 'exports_files(["cc_shim.bzl"])\n')
    rctx.file("cc_shim.bzl", template.format(version = version))

cc_shim_repo = repository_rule(
    implementation = _cc_shim_repo_impl,
    # `local = True` re-evaluates on server restart so `native.bazel_version` stays current.
    local = True,
    attrs = {
        "bazel_version": attr.string(
            doc = "Override Bazel version for testing; falls back to `native.bazel_version`.",
        ),
    },
)

def _cc_shim_extension_impl(_ctx):
    cc_shim_repo(name = "rules_graalvm_cc_shim")

cc_shim_extension = module_extension(
    implementation = _cc_shim_extension_impl,
    doc = "Generates `@rules_graalvm_cc_shim//:cc_shim.bzl` adapted to the running Bazel version.",
)
